openapi: 3.0.3
info:
  title: SGBR-API
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/places:
    get:
      summary: 'Places list'
      operationId: placesList
      description: 'This endpoint return the list of places.'
      parameters:
        -
          in: query
          name: name
          description: 'The place name.'
          example: fugiat
          required: false
          schema:
            type: string
            description: 'The place name.'
            example: fugiat
        -
          in: query
          name: per_page
          description: 'The number of items to be returned per page `default: 10`. Must be at least 1. Must not be greater than 100.'
          example: 16
          required: false
          schema:
            type: integer
            description: 'The number of items to be returned per page `default: 10`. Must be at least 1. Must not be greater than 100.'
            example: 16
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: '51817 Dewitt Bridge'
                      slug: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                      city: 'Port Joshuaberg'
                      state: 'sint tenetur'
                      created_at: '2023-06-23T13:47:53.000000Z'
                      updated_at: '2023-06-23T13:47:53.000000Z'
                    -
                      id: 2
                      name: '639 Aufderhar Junction Apt. 649'
                      slug: 639-aufderhar-junction-apt-649-at-kaelynmouth-at-deleniti-aut
                      city: Kaelynmouth
                      state: 'deleniti aut'
                      created_at: '2023-06-23T13:47:53.000000Z'
                      updated_at: '2023-06-23T13:47:53.000000Z'
                  links:
                    first: 'http://localhost/api/v1/places?page=1'
                    last: 'http://localhost/api/v1/places?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/places?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/v1/places'
                    per_page: 10
                    to: 10
                    total: 10
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: '51817 Dewitt Bridge'
                        slug: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                        city: 'Port Joshuaberg'
                        state: 'sint tenetur'
                        created_at: '2023-06-23T13:47:53.000000Z'
                        updated_at: '2023-06-23T13:47:53.000000Z'
                      -
                        id: 2
                        name: '639 Aufderhar Junction Apt. 649'
                        slug: 639-aufderhar-junction-apt-649-at-kaelynmouth-at-deleniti-aut
                        city: Kaelynmouth
                        state: 'deleniti aut'
                        created_at: '2023-06-23T13:47:53.000000Z'
                        updated_at: '2023-06-23T13:47:53.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: '51817 Dewitt Bridge'
                        slug:
                          type: string
                          example: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                        city:
                          type: string
                          example: 'Port Joshuaberg'
                        state:
                          type: string
                          example: 'sint tenetur'
                        created_at:
                          type: string
                          example: '2023-06-23T13:47:53.000000Z'
                        updated_at:
                          type: string
                          example: '2023-06-23T13:47:53.000000Z'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/v1/places?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/v1/places?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/v1/places?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/v1/places'
                      per_page:
                        type: integer
                        example: 10
                      to:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 10
      tags:
        - Place
      security: []
    post:
      summary: 'New place'
      operationId: newPlace
      description: 'This endpoint create a new place.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: '51817 Dewitt Bridge'
                    slug: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                    city: 'Port Joshuaberg'
                    state: 'sint tenetur'
                    created_at: '2023-06-23T13:47:53.000000Z'
                    updated_at: '2023-06-23T13:47:53.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: '51817 Dewitt Bridge'
                      slug:
                        type: string
                        example: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                      city:
                        type: string
                        example: 'Port Joshuaberg'
                      state:
                        type: string
                        example: 'sint tenetur'
                      created_at:
                        type: string
                        example: '2023-06-23T13:47:53.000000Z'
                      updated_at:
                        type: string
                        example: '2023-06-23T13:47:53.000000Z'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  errors:
                    name:
                      - 'The name field is required.'
                      - 'The name field must be a string.'
                      - 'The name field must not be greater than 255 characters.'
                    city:
                      - 'The city field is required.'
                      - 'The city field must be a string.'
                      - 'The city field must not be greater than 255 characters.'
                    state:
                      - 'The state field is required.'
                      - 'The state field must be a string.'
                      - 'The state field must not be greater than 255 characters.'
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name field is required.'
                          - 'The name field must be a string.'
                          - 'The name field must not be greater than 255 characters.'
                        items:
                          type: string
                      city:
                        type: array
                        example:
                          - 'The city field is required.'
                          - 'The city field must be a string.'
                          - 'The city field must not be greater than 255 characters.'
                        items:
                          type: string
                      state:
                        type: array
                        example:
                          - 'The state field is required.'
                          - 'The state field must be a string.'
                          - 'The state field must not be greater than 255 characters.'
                        items:
                          type: string
      tags:
        - Place
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The place name. Must not be greater than 255 characters.'
                  example: iqxtwwehqgxhvmfwbdtahest
                city:
                  type: string
                  description: 'The city name. Must not be greater than 255 characters.'
                  example: ohieliccydgsd
                state:
                  type: string
                  description: 'The state name. Must not be greater than 255 characters.'
                  example: xpusgul
              required:
                - name
                - city
                - state
      security: []
  '/api/v1/places/{id}':
    get:
      summary: 'Find place'
      operationId: findPlace
      description: 'This endpoint return a place.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: '51817 Dewitt Bridge'
                    slug: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                    city: 'Port Joshuaberg'
                    state: 'sint tenetur'
                    created_at: '2023-06-23T13:47:53.000000Z'
                    updated_at: '2023-06-23T13:47:53.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: '51817 Dewitt Bridge'
                      slug:
                        type: string
                        example: 51817-dewitt-bridge-at-port-joshuaberg-at-sint-tenetur
                      city:
                        type: string
                        example: 'Port Joshuaberg'
                      state:
                        type: string
                        example: 'sint tenetur'
                      created_at:
                        type: string
                        example: '2023-06-23T13:47:53.000000Z'
                      updated_at:
                        type: string
                        example: '2023-06-23T13:47:53.000000Z'
      tags:
        - Place
      security: []
    put:
      summary: 'Update a place'
      operationId: updateAPlace
      description: 'This endpoint update a place.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Place updated.'
                properties:
                  message:
                    type: string
                    example: 'Place updated.'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  errors:
                    name:
                      - 'The name field must have a value.'
                      - 'The name field must be a string.'
                      - 'The name field must not be greater than 255 characters.'
                    city:
                      - 'The city field must have a value.'
                      - 'The city field must be a string.'
                      - 'The city field must not be greater than 255 characters.'
                    state:
                      - 'The state field must have a value.'
                      - 'The state field must be a string.'
                      - 'The state field must not be greater than 255 characters.'
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name field must have a value.'
                          - 'The name field must be a string.'
                          - 'The name field must not be greater than 255 characters.'
                        items:
                          type: string
                      city:
                        type: array
                        example:
                          - 'The city field must have a value.'
                          - 'The city field must be a string.'
                          - 'The city field must not be greater than 255 characters.'
                        items:
                          type: string
                      state:
                        type: array
                        example:
                          - 'The state field must have a value.'
                          - 'The state field must be a string.'
                          - 'The state field must not be greater than 255 characters.'
                        items:
                          type: string
      tags:
        - Place
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The place name. Must not be greater than 255 characters.'
                  example: gdmtgfuhvmiyjemqceyo
                city:
                  type: string
                  description: 'The city name. Must not be greater than 255 characters.'
                  example: hpkwxjhbrkjbnjdnrpou
                state:
                  type: string
                  description: 'The state name. Must not be greater than 255 characters.'
                  example: a
      security: []
    delete:
      summary: 'Delete a place'
      operationId: deleteAPlace
      description: 'This endpoint delete a place.'
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Place
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the place.'
        example: 10
        required: true
        schema:
          type: integer
tags:
  -
    name: Place
    description: ''
